### ISSUE TITLE
CSS returning 404

### ISSUE THREAD

**Issue by jridgewell** [benschwarz/bonsai#1]
Whenever I cultivate, the server looks for my css files inside of ROOT/content/css. Shouldn't this be looking for CSS inside the ROOT/public/docs/css or ROOT/output/docs/css?

<pre><code>$ bonsai --cultivate

  
  盆栽
  bonsai, tiny and beautiful
  
Copying public files
Copying page assets
Copying public files
Copying page assets
>> Thin web server (v1.2.5 codename This Is Not A Web Server)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:5000, CTRL+C to stop
!! Unexpected error while processing request: page 'css/base.css' not found at '/Users/test/Sites/rails/test/content'
!! Unexpected error while processing request: page 'css/base.css' not found at '/Users/test/Sites/rails/test/content'
</code></pre>

**Comment by benschwarz** [comment]
The server is correct, but the path in the example HTML is incorrect. 
You will need to prepend /docs/ to the path so that it reads /docs/css/base.css

I have fixed this (yesterday) however it has not yet been released as a gem. 
I'll leave this issue open until such time.

**Comment by benschwarz** [comment]
1.1.1 closes this issue.
