### ISSUE TITLE
Rack error when using bonsai commands

### ISSUE THREAD

**Issue by jacksonfox** [benschwarz/bonsai#15]
I get the following error whenever I try to use bonsai from the commandline:

```
/Library/Ruby/Site/1.8/rubygems.rb:233:in `activate': can't activate rack (= 1.1.0, runtime) for ["bonsai-1.3.1"], already activated rack-1.2.1 for ["sinatra-0.9.4", "bonsai-1.3.1"] (Gem::LoadError)
    from /Library/Ruby/Site/1.8/rubygems.rb:249:in `activate'
    from /Library/Ruby/Site/1.8/rubygems.rb:248:in `each'
    from /Library/Ruby/Site/1.8/rubygems.rb:248:in `activate'
    from /Library/Ruby/Site/1.8/rubygems.rb:1082:in `gem'
    from /usr/bin/bonsai:18
```

Using Mac OS X 10.6.4, Ruby 1.87

**Comment by benschwarz** [comment]
You've got a newer version of these gems on your system and they're being required in place of the versions that bonsai would normally use. 
You could remove the newer version of rack or could maybe use a bundler "gemenv" to only have the correct gems installed when you `gem install bonsai`
