### ISSUE TITLE
Static Coffeescript

### ISSUE THREAD

**Issue by DanielHeath** [benschwarz/bonsai#16]
I've been giving Bonsai a try and found there wasn't a clear 'preferred way' to do something, so I thought I'd ask what you thought.

I've been using Coffeescript for awhile now, and it seems like the best way to go, but I don't really want anything dynamic for it other than generating the static .js files.
Nor do I want it showing up in the navigation.

Should it go under public/js (like LessCSS files do)?

**Comment by benschwarz** [comment]
Yeah I think that `public/js` is the way to go for this. Being that Bonsai's core focus is really small, simple sites—I think that provisioning for a dynamic 'app like' framework is overkill. 

So if you're thinking of patching it for yourself, please send me a pull request :-)

**Comment by benschwarz** [comment]
If you're feeling overly generous—I'd love a patch to switch LessCSS out for SCSS. 
Its just my preference now that LessCSS has been more or less abandoned (as a ruby project) and the current implementation has a poor parser that likes to crash with certain CSS expressions.

**Comment by DanielHeath** [comment]
In the end, I went for something a bit more app-like. 
It'd still be a good thing to have in Bonsai, and I think I'd add it if I was going to use it in anger.
