### ISSUE TITLE
New Versions of Sinatra Require Tilt >= 1.2.2, Bonsai requires tilt ~> 0.9

### ISSUE THREAD

**Issue by flowerornament** [benschwarz/bonsai#17]
There is a conflict when installing the bonsai gem. Bonsai requires tilt ~> 0.9 in order to have mustache support, however recent sinatra versions require a newer version of tilt. 

I would suggest dropping mustache, since it's no longer supported in tilt, and going with liquid as the default. If that's too unpalatable, then you should require sinatra ~> 1.0.b.

I'm sad to see this project fall into disrepair. I wanted to use it for a website, but unfortunately I have to turn it down in favor of nanoc due to lack of support.

**Comment by benschwarz** [comment]
I think your suggestions are good, and I've had a few emails about it recently… so I'd like to at least have it in a working state. I'll investigate your suggestions when I get back to Australia.

**Comment by benschwarz** [comment]
Or… feel free to send me a patch and be immortalized in README.md :)

**Comment by adrianocastro** [comment]
I’ve been bitten by this too. It’s been a long while since this issue was raised. Any updates on a possible fix?

**Comment by adrianocastro** [comment]
It would be a shame to drop mustache support. I found someone who was working on [adding mustache to tilt](https://github.com/Becojo/tilt-mustache).

**Comment by benschwarz** [comment]
@adrianocastro, Mustache used to be a part of tilt and was removed by the author of tilt, @rtomayko. 
I don't see it coming in again. 

I have an unpublished branch of bonsai that requires some cleanup (although its passing the test suite from memory) which converted to using liquid and removed tilt all together. 

Not sure if you're interested in trying to do that cleanup yourself, but I don't really have the time to get into it right now or in the next couple of weeks :/

**Comment by adrianocastro** [comment]
@benschwarz, I’m not particularly well versed in Ruby but I’d love to have a look at it.

**Comment by benschwarz** [comment]
Ok. I'll push my branch to github later.

**Comment by benschwarz** [comment]
I've just pushed 1.4 to rubygems, I've removed mustache as versions newer than 0.6 were doing crazy things. I'm sure it could be added back without too much pain, but either way. 

If you could all kick the tyres for 1.4 and report back any issues, I'd appreciate it.
The readme has been updated, but the website has not been yet, so substitute everything it tells you about "mustache" for "liquid" :)
