### ISSUE TITLE
Error while attempting to install the latest version

### ISSUE THREAD

**Issue by zimmerman1181** [benschwarz/bonsai#20]
When attempting to install via:  

> gem install bonsai --source http://gemcutter.org

The command line kicks back the following error:

> ERROR:  While executing gem ... (ArgumentError)
>    Illformed requirement ["#YAML::Syck::DefaultKey:0x102feb6d8 1.0"]

**Comment by benschwarz** [comment]
Firstly, gemcutter.com is now rubygems.org, so there shouldn't be any need to set the host. 
Now, the actual issue is strange and something that I've never seen from rubygems. 

What version of rubygems are you using? 

I just checked the updates for the latest gem version and saw: 
- Fixed Syck DefaultKey infecting ruby-format specifications.

So I think you've found a known issue—I'd try updating rubygems (using `gem update --system).

**Comment by benschwarz** [comment]
I just had a chat with @drbrain in #rubygems on freenode, he suggested that I rebuild the gem ensuring that I have rubygems 1.8.10—

I've done that and pushed a new gem release - bonsai 1.4.1

http://rubygems.org/gems/bonsai

**Comment by zimmerman1181** [comment]
I tried updating to the latest gem when I first got the error, but I'm somewhat of a novice so could have easily been doing something wrong. I'll try again and let you know how it goes.

**Comment by benschwarz** [comment]
No hassles. Any issues—Let me know.

**Comment by zimmerman1181** [comment]
Ok...this is weird. I made sure I had rubygems 1.8.10, then tried installing bonsai via:
gem install bonsai

And after fetching all of the dependencies, I get:
ERROR:  Error installing bonsai:
    bonsai requires bonsai (>= 0)

**Comment by benschwarz** [comment]
Whoa. That IS weird. It looks like the tool (jeweler) decided to make bonsai a dependency of itself!
I just did a quick fix and release 1.4.2!

**Comment by zimmerman1181** [comment]
You're going to hate me. :)
It installed and I thought we were about to rock and roll, but now anytime I type a bonsai command I get a LoadError. For example:

$ bonsai --help
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- bundler/setup (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/bonsai-1.4.2/bin/bonsai:4
    from /usr/bin/bonsai:19:in `load'
    from /usr/bin/bonsai:19

**Comment by benschwarz** [comment]
I totally don't… the issue you've just hit was totally my fault!
I've just done _another_ gem release (1.4.3) which seems to be doing everything it should. 

Good luck!

**Comment by zimmerman1181** [comment]
Woohoo! Now we're cookin' with fire. Thanks for the speedy assistance Ben!

**Comment by vemek** [comment]
I'm seeing this issue again, unfortunately:

```
$ gem -v
1.8.24
$ gem install bonsai
ERROR:  Error installing bonsai:
    bonsai requires bonsai (>= 0)
```

It also seems to list itself as a dependency here: http://rubygems.org/gems/bonsai

**Comment by benschwarz** [comment]
Damnit! This is the jewelry gem playing havoc again.

I'll reissue another gem when I get to the office

**Comment by benschwarz** [comment]
Give 1.4.7 a spin!

**Comment by vemek** [comment]
Works a charm, thanks :)

On 30 June 2012 23:22, Ben Schwarz <
reply@reply.github.com

**Comment by benschwarz** [comment]
Great stuff. Thanks for the quick response.
