### ISSUE TITLE
Link to tinytree.com in template project broken

### ISSUE THREAD

**Issue by sport4minus** [benschwarz/bonsai#26]
Link in "Built with Bonsai" in footer of default page points to www.tinytree.info instead of tinytree.info, and ends up showing an error.

Dear Ben, just pointing this out to say thank you for Bonsai. You choose where to fix the "Issue"
- J

**Comment by benschwarz** [comment]
Thanks so much for the report. I must've missed setting up the `www` when I moved the hosting to S3. 
Fixed! Cheers.
