### ISSUE TITLE
Cannot install gem

### ISSUE THREAD

**Issue by DanielHeath** [benschwarz/bonsai#28]
$ gem -v
1.8.10

$ ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.3.0]

$ gem install bonsai
Fetching: rack-protection-1.2.0.gem (100%)
Fetching: tilt-1.3.3.gem (100%)
Fetching: sinatra-1.3.2.gem (100%)
Fetching: builder-3.0.0.gem (100%)
Fetching: watch-0.1.0.gem (100%)
Fetching: launchy-2.1.0.gem (100%)
Fetching: activesupport-3.2.6.gem (100%)
Fetching: sass-3.1.20.gem (100%)
Fetching: bonsai-1.4.6.gem (100%)
ERROR:  Error installing bonsai:
    bonsai requires bonsai (>= 0)

gem install bonsai --ignore-dependencies # works fine
gem install bonsai # works fine once bonsai is installed

$ bonsai --plant bonsai-test
/Users/danielheath/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb:41: stack level too deep (SystemStackError)

It looks as though bonsai is requiring bonsai (infinite recursion)

**Comment by benschwarz** [comment]
Thanks for the issue… this popped up last week (written up in #20).
I'm looking at it right now!

**Comment by benschwarz** [comment]
Give 1.4.7 a spin!

**Comment by benschwarz** [comment]
Super. Closing.
