### ISSUE TITLE
site.yml variables: unable to / (non-obvious) access in templates

### ISSUE THREAD

**Issue by kematzy** [benschwarz/bonsai#3]
Just found out about Bonsai, and is trying it out, but I found this issue:

How do you access the variables in the site.yml file inside your templates/partials ?

Haven't got the time to carefully study the code atm, but I couldn't get it after a quick glance.

**Comment by benschwarz** [comment]
Actually, they haven't been made available to the page. 
I was more provisioning a space for the idea – I'll implement this for the next release.

**Comment by benschwarz** [comment]
I've just released 1.1.4. You'll need to regenerate the site framework to see the changes.
http://github.com/benschwarz/bonsai/blob/master/CHANGES
