### ISSUE TITLE
Gem install fail

### ISSUE THREAD

**Issue by juytter** [benschwarz/bonsai#38]
`ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]`

`Building native extensions.  This could take a while...
ERROR:  Error installing bonsai:
ERROR: Failed to build gem native extension.
 current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.11.3/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20200113-779-1uovf7c.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h`

**Comment by benschwarz** [comment]
It looks like you're on a mac - but require `libffi`. 

Assuming you have homebrew your machine, install libffi using `brew install libffi`.

After that you should be able to successfully run `gem install bonsai`

Could you follow those steps and report back?

**Comment by juytter** [comment]
Well i just re install and update Ruby,  it's work. Sorry. Close.
