### ISSUE TITLE
Why a docs/ directory with /css & /js dirs inside ?

### ISSUE THREAD

**Issue by kematzy** [benschwarz/bonsai#4]
I don't understand the logic behind storing _css_ & _js_ dirs inside a _docs_ directory as well.

"docs" is commonly used for documentation (ie: rdocs etc), while "css" & "js" are commonly used at the root of the server.

Is it an implementation issue, or just your preference?

**Comment by benschwarz** [comment]
"docs" doesn't refer to "documentation", in this case it refers to "documents". 
Its an old habit that I have with small web sites to keep the public area cleaner. 

While this is what the generator gives you, you're free to do whatever you like.
