### ISSUE TITLE
ri / RDoc Unrecognized directives

### ISSUE THREAD

**Issue by feelepxyz** [benschwarz/bonsai#5]
Got this output when updating the gem.. 
1.9.1 on OS X. 

---

Installing ri documentation for bonsai-1.1.4...
Unrecognized directive 'headline' in lib/bonsai/templates/content/1.varieties/1.fig/default.yml
Unrecognized directive 'headline' in lib/bonsai/templates/content/1.varieties/2.maple/default.ymlUnrecognized directive 'body' in lib/bonsai/templates/content/1.varieties/1.fig/default.yml
Unrecognized directive 'body' in lib/bonsai/templates/content/1.varieties/2.maple/default.yml

Unrecognized directive 'headline' in lib/bonsai/templates/content/2.cultivation/default.ymlUnrecognized directive 'headline' in lib/bonsai/templates/content/1.varieties/products.yml

Unrecognized directive 'body' in lib/bonsai/templates/content/2.cultivation/default.yml
Unrecognized directive 'headline' in lib/bonsai/templates/content/3.history/default.ymlUnrecognized directive 'headline' in lib/bonsai/templates/content/index/default.yml

Unrecognized directive 'body' in lib/bonsai/templates/content/3.history/default.ymlUnrecognized directive 'body' in lib/bonsai/templates/content/index/default.yml

Unrecognized directive 'site_name' in lib/bonsai/templates/site.yml
Unrecognized directive 'url' in lib/bonsai/templates/site.yml
Unrecognized directive 'copyright' in lib/bonsai/templates/site.yml
Building YARD (yri) index for bonsai-1.1.4...
ERROR:  While generating documentation for bonsai-1.1.4
... MESSAGE:   No such file or directory - Could not find extra file: README.rdoc
... YARDDOC args: -c -n --quiet lib - LICENSE README.md
(continuing with the rest of the installation)

---

Installing RDoc documentation for bonsai-1.1.4...
Unrecognized directive 'headline' in lib/bonsai/templates/content/1.varieties/1.fig/default.yml
Unrecognized directive 'body' in lib/bonsai/templates/content/1.varieties/1.fig/default.yml
Unrecognized directive 'headline' in lib/bonsai/templates/content/1.varieties/2.maple/default.yml
Unrecognized directive 'body' in lib/bonsai/templates/content/1.varieties/2.maple/default.yml
Unrecognized directive 'headline' in lib/bonsai/templates/content/1.varieties/products.yml
Unrecognized directive 'headline' in lib/bonsai/templates/content/2.cultivation/default.yml
Unrecognized directive 'body' in lib/bonsai/templates/content/2.cultivation/default.ymlUnrecognized directive 'headline' in lib/bonsai/templates/content/3.history/default.yml

Unrecognized directive 'body' in lib/bonsai/templates/content/3.history/default.yml
Unrecognized directive 'headline' in lib/bonsai/templates/content/index/default.yml
Unrecognized directive 'body' in lib/bonsai/templates/content/index/default.yml
Unrecognized directive 'site_name' in lib/bonsai/templates/site.yml
Unrecognized directive 'url' in lib/bonsai/templates/site.yml
Unrecognized directive 'copyright' in lib/bonsai/templates/site.yml

**Comment by benschwarz** [comment]
Thanks. I noticed this yesterday and haven't worked out why as yet. 
I'll look into it for the next release

**Comment by benschwarz** [comment]
Its worth noting that the gem installs perfectly despite this scary looking output.

**Comment by feelepxyz** [comment]
yeah, love it btw! totally underrated if you ask me :) 
Something that popped into my head. Is it possible to render ruby code as a variable in a mustache template? 
Something like, :copyright: #{Time.now.year} ..

**Comment by benschwarz** [comment]
No - For more dynamic templates you might want to try something other than mustache. Although keep it in mind that mustache is the only one with built in partial support. Also, if you can post queries like this one to the google group, it would be awesome. (Better information sharing)

**Comment by benschwarz** [comment]
Fixed in 1.1.5
