### ISSUE TITLE
Index is created both as a directory and as /index.html

### ISSUE THREAD

**Issue by dgoodlad** [benschwarz/bonsai#9]
The index page should only exist as /index.html. Right now, Bonsai generates /index.html AND /index/index.html. Both are put into the sitemap.xml as well. This is bad for all sorts of reasons.

http://github.com/benschwarz/bonsai/blob/master/lib/bonsai/sitemap.rb#L16 was identified as the source for it going into the sitemap (checking === '/index' is wrong, as permalinks have trailing slashes now).

**Comment by robinpokorny** [comment]
The easiest way how to solve it is to make /index.html redirect to /index/index.html. That could be done by:

/index.html:

<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title></title><meta http-equiv="refresh" content="0;url= index/" /></head><body></body></html>

That would be a logical solution, however the best one is not to generate /index/index.html at all.
